# Site identity
title: "Hossein Mahani"
description: "Mechanical Engineer | Additive Manufacturing, Nanocomposites, Powder Processing"
url: "https://hosseinmahani.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  
just_the_docs:
 css_url: "/assets/css/custom.css"  # Ensure this is correct path to your custom CSS file

# --- Just the Docs options ---
# Sidebar profile photo (use a large square image; the theme will display it in the sidebar)
logo: /assets/img/headshot.jpg
# (Optional) alt text for accessibility
logo_alt: "Portrait of Hossein Mahani"

search_enabled: false
color_scheme: light
heading_anchors: true



# SEO (optional but nice)
title_separator: "•"
permalink: pretty



# Build
markdown: kramdown
kramdown:
  input: GFM
