# Site identity
title: "Hossein Mahani"
description: "Mechanical Engineer | Additive Manufacturing, Nanocomposites, Powder Processing"
url: "https://hosseinmahani.github.io"

# Theme
# Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  color_scheme: dark

# --- Just the Docs options ---
# Sidebar profile photo (use a large square image; the theme will display it in the sidebar)
logo: /assets/img/headshot.jpg
# (Optional) alt text for accessibility
logo_alt: "Portrait of Hossein Mahani"

search_enabled: true
color_scheme: light
heading_anchors: true

# Navigation
# The sidebar menu is built from your pages.
# Set these files with front matter and nav_order in each page:
#   index.md            -> About (nav_order: 1)
#   publications.md     -> Publications (nav_order: 2)
#   cv.md               -> CV (nav_order: 3)
#   contact.md          -> Contact (nav_order: 4)
#
# We intentionally DO NOT use nav_external_links or aux_links,
# so no email/phone appears in the sidebar (Contact page handles that).

# Exclude any pages you don’t want in the sidebar (add their paths here if needed)
# nav_exclude: 
#   - patents.md

# SEO (optional but nice)
title_separator: "•"
permalink: pretty

# Sitemap + robots (optional)
# jekyll-sitemap is built into GitHub Pages; enable if you add plugins list later.
# plugins:
#   - jekyll-remote-theme
#   - jekyll-sitemap

# Build
markdown: kramdown
kramdown:
  input: GFM
