
title: "Hossein Mahani"
description: "Mechanical Engineer | Additive Manufacturing, Nanocomposites, Powder Processing"
# GitHub Pages Jekyll theme (no local install needed)
remote_theme: "just-the-docs/just-the-docs"
plugins:
  - jekyll-remote-theme

# Just the Docs options
just_the_docs:
  search_enabled: false
  color_scheme: light

# Site settings
author:
  name: "Hossein Mahani"
  email: "h.mmahani@gmail.com"
  affiliation: "Isfahan University of Technology"
  location: "Isfahan, Iran"

# Nav (shows at top)
nav:
  - name: "About"
    link: /
  - name: "Publications"
    link: /publications
  - name: "Patents"
    link: /patents
  - name: "CV"
    link: /cv
  - name: "Contact"
    link: /contact

# SEO
url: "https://hosseinmahani.github.io"
